const { normalizeLanguage } = require('./tmdbLocale');

const LANGS = ['en', 'fr', 'de', 'es', 'it', 'nl', 'pt', 'no', 'da', 'sv', 'fi'];

function langShort(language) {
  const code = normalizeLanguage(language).split('-')[0].toLowerCase();
  return LANGS.includes(code) ? code : 'en';
}

/** Common certification codes → localized short meanings (TMDB has EN-only meanings). */
const CERT_MEANINGS = {
  G: {
    en: 'General audiences',
    fr: 'Tout public',
    de: 'Freigegeben ohne Altersbeschränkung',
    es: 'Para todos los públicos',
    it: 'Per tutti',
    nl: 'Alle leeftijden',
    pt: 'Para todos os públicos',
    no: 'For alle',
    da: 'Tilladt for alle',
    sv: 'Barntillåten',
    fi: 'Kaikenikäisille',
  },
  PG: {
    en: 'Parental guidance suggested',
    fr: 'Accord parental souhaitable',
    de: 'Empfohlen ab 6 Jahren',
    es: 'Se recomienda supervisión parental',
    it: 'Consigliata la supervisione dei genitori',
    nl: 'Ouderlijk toezicht aanbevolen',
    pt: 'Recomendada supervisão parental',
    no: 'Foreldreveiledning anbefales',
    da: 'Forældrevejledning anbefales',
    sv: 'Rekommenderas med föräldrar',
    fi: 'Vanhempien valvonta suositeltavaa',
  },
  'PG-13': {
    en: 'Parents strongly cautioned',
    fr: 'Déconseillé aux moins de 13 ans',
    de: 'Ab 13 Jahren empfohlen',
    es: 'No recomendado para menores de 13 años',
    it: 'Sconsigliato ai minori di 13 anni',
    nl: 'Niet aanbevolen onder 13 jaar',
    pt: 'Desaconselhado para menores de 13 anos',
    no: 'Ikke anbefalt under 13 år',
    da: 'Ikke anbefalet under 13 år',
    sv: 'Ej rekommenderat under 13 år',
    fi: 'Ei suositella alle 13-vuotiaille',
  },
  R: {
    en: 'Restricted — under 17 requires accompanying parent or adult guardian',
    fr: 'Interdit aux moins de 17 ans sans accompagnement',
    de: 'Ab 17 Jahren (Jugendliche nur mit Erziehungsberechtigtem)',
    es: 'Restringida — menores de 17 con acompañante adulto',
    it: 'Vietato ai minori di 17 anni non accompagnati',
    nl: 'Geen toegang onder 17 zonder begeleiding',
    pt: 'Proibido a menores de 17 sem acompanhante',
    no: 'Begrenset — under 17 krever følge',
    da: 'Forbudt for under 17 uden ledsager',
    sv: 'Begränsad — under 17 kräver sällskap',
    fi: 'Kielletty alle 17-vuotiailta ilman aikuista',
  },
  'NC-17': {
    en: 'Adults only — no one 17 and under admitted',
    fr: 'Réservé aux adultes — interdit aux moins de 18 ans',
    de: 'Nur für Erwachsene ab 18',
    es: 'Solo adultos — prohibido a menores de 18',
    it: 'Solo adulti — vietato ai minori di 18',
    nl: 'Alleen volwassenen — geen toegang onder 18',
    pt: 'Apenas adultos — proibido a menores de 18',
    no: 'Kun voksne — ingen under 18',
    da: 'Kun voksne — ingen under 18',
    sv: 'Endast vuxna — ingen under 18',
    fi: 'Vain aikuisille — alle 18-vuotiaat kielletty',
  },
  'TV-Y': {
    en: 'All children',
    fr: 'Tous les enfants',
    de: 'Für alle Kinder',
    es: 'Para todos los niños',
    it: 'Per tutti i bambini',
    nl: 'Voor alle kinderen',
    pt: 'Para todas as crianças',
    no: 'For alle barn',
    da: 'For alle børn',
    sv: 'För alla barn',
    fi: 'Kaikille lapsille',
  },
  'TV-Y7': {
    en: 'Directed to older children',
    fr: 'Destiné aux enfants plus âgés (7+)',
    de: 'Für Kinder ab 7 Jahren',
    es: 'Dirigido a niños mayores (7+)',
    it: 'Per bambini più grandi (7+)',
    nl: 'Voor oudere kinderen (7+)',
    pt: 'Para crianças mais velhas (7+)',
    no: 'For eldre barn (7+)',
    da: 'For ældre børn (7+)',
    sv: 'För äldre barn (7+)',
    fi: 'Vanhemmille lapsille (7+)',
  },
  'TV-G': {
    en: 'General audience',
    fr: 'Tout public',
    de: 'Freigegeben ohne Altersbeschränkung',
    es: 'Para todo público',
    it: 'Per tutti',
    nl: 'Algemeen publiek',
    pt: 'Para todo o público',
    no: 'For alle',
    da: 'For alle',
    sv: 'Allmän publik',
    fi: 'Kaikenikäisille',
  },
  'TV-PG': {
    en: 'Parental guidance suggested',
    fr: 'Accord parental souhaitable',
    de: 'Empfohlen mit elterlicher Begleitung',
    es: 'Se recomienda supervisión parental',
    it: 'Consigliata la supervisione dei genitori',
    nl: 'Ouderlijk toezicht aanbevolen',
    pt: 'Recomendada supervisão parental',
    no: 'Foreldreveiledning anbefales',
    da: 'Forældrevejledning anbefales',
    sv: 'Rekommenderas med föräldrar',
    fi: 'Vanhempien valvonta suositeltavaa',
  },
  'TV-14': {
    en: 'Parents strongly cautioned',
    fr: 'Déconseillé aux moins de 14 ans',
    de: 'Ab 14 Jahren empfohlen',
    es: 'No recomendado para menores de 14 años',
    it: 'Sconsigliato ai minori di 14 anni',
    nl: 'Niet aanbevolen onder 14 jaar',
    pt: 'Desaconselhado para menores de 14 anos',
    no: 'Ikke anbefalt under 14 år',
    da: 'Ikke anbefalet under 14 år',
    sv: 'Ej rekommenderat under 14 år',
    fi: 'Ei suositella alle 14-vuotiaille',
  },
  'TV-MA': {
    en: 'Mature audience only',
    fr: 'Public mature uniquement',
    de: 'Nur für Erwachsene',
    es: 'Solo público adulto',
    it: 'Solo pubblico adulto',
    nl: 'Alleen volwassenen',
    pt: 'Apenas público adulto',
    no: 'Kun voksne',
    da: 'Kun voksne',
    sv: 'Endast vuxna',
    fi: 'Vain aikuisille',
  },
  U: {
    en: 'Universal — suitable for all',
    fr: 'Tout public (UK)',
    de: 'Freigegeben ab 0 (UK)',
    es: 'Para todos (UK)',
    it: 'Per tutti (UK)',
    nl: 'Alle leeftijden (UK)',
    pt: 'Para todos (UK)',
    no: 'For alle (UK)',
    da: 'For alle (UK)',
    sv: 'Barntillåten (UK)',
    fi: 'Kaikenikäisille (UK)',
  },
  '12A': {
    en: 'Cinema: under 12 must be with an adult',
    fr: 'Cinéma : moins de 12 ans accompagné (UK)',
    de: 'Kino: unter 12 nur mit Erwachsenem (UK)',
    es: 'Cine: menores de 12 con adulto (UK)',
    it: 'Cinema: under 12 con adulto (UK)',
    nl: 'Bioscoop: onder 12 met volwassene (UK)',
    pt: 'Cinema: menores de 12 com adulto (UK)',
    no: 'Kino: under 12 med voksen (UK)',
    da: 'Biograf: under 12 med voksen (UK)',
    sv: 'Bio: under 12 med vuxen (UK)',
    fi: 'Elokuva: alle 12 vain aikuisen seurassa (UK)',
  },
  12: {
    en: 'Suitable for 12 and over',
    fr: 'À partir de 12 ans (UK)',
    de: 'Ab 12 Jahren (UK)',
    es: 'A partir de 12 años (UK)',
    it: 'Da 12 anni (UK)',
    nl: 'Vanaf 12 jaar (UK)',
    pt: 'A partir dos 12 anos (UK)',
    no: 'Fra 12 år (UK)',
    da: 'Fra 12 år (UK)',
    sv: 'Från 12 år (UK)',
    fi: 'Yli 12-vuotiaille (UK)',
  },
  15: {
    en: 'Suitable for 15 and over',
    fr: 'À partir de 15 ans (UK)',
    de: 'Ab 15 Jahren (UK)',
    es: 'A partir de 15 años (UK)',
    it: 'Da 15 anni (UK)',
    nl: 'Vanaf 15 jaar (UK)',
    pt: 'A partir dos 15 anos (UK)',
    no: 'Fra 15 år (UK)',
    da: 'Fra 15 år (UK)',
    sv: 'Från 15 år (UK)',
    fi: 'Yli 15-vuotiaille (UK)',
  },
  18: {
    en: 'Suitable for 18 and over',
    fr: 'À partir de 18 ans (UK)',
    de: 'Ab 18 Jahren (UK)',
    es: 'A partir de 18 años (UK)',
    it: 'Da 18 anni (UK)',
    nl: 'Vanaf 18 jaar (UK)',
    pt: 'A partir dos 18 anos (UK)',
    no: 'Fra 18 år (UK)',
    da: 'Fra 18 år (UK)',
    sv: 'Från 18 år (UK)',
    fi: 'Yli 18-vuotiaille (UK)',
  },
  'FSK 0': {
    en: 'Released without age restriction',
    fr: 'Sans limite d’âge (Allemagne)',
    de: 'Freigegeben ohne Altersbeschränkung',
    es: 'Sin restricción de edad (Alemania)',
    it: 'Senza limiti di età (Germania)',
    nl: 'Geen leeftijdsbeperking (Duitsland)',
    pt: 'Sem restrição de idade (Alemanha)',
    no: 'Ingen aldersgrense (Tyskland)',
    da: 'Ingen aldersgrænse (Tyskland)',
    sv: 'Ingen åldersgräns (Tyskland)',
    fi: 'Ei ikärajaa (Saksa)',
  },
  'FSK 6': {
    en: 'Released from age 6',
    fr: 'À partir de 6 ans (Allemagne)',
    de: 'Freigegeben ab 6 Jahren',
    es: 'A partir de 6 años (Alemania)',
    it: 'Da 6 anni (Germania)',
    nl: 'Vanaf 6 jaar (Duitsland)',
    pt: 'A partir dos 6 anos (Alemanha)',
    no: 'Fra 6 år (Tyskland)',
    da: 'Fra 6 år (Tyskland)',
    sv: 'Från 6 år (Tyskland)',
    fi: 'Yli 6-vuotiaille (Saksa)',
  },
  'FSK 12': {
    en: 'Released from age 12',
    fr: 'À partir de 12 ans (Allemagne)',
    de: 'Freigegeben ab 12 Jahren',
    es: 'A partir de 12 años (Alemania)',
    it: 'Da 12 anni (Germania)',
    nl: 'Vanaf 12 jaar (Duitsland)',
    pt: 'A partir dos 12 anos (Alemanha)',
    no: 'Fra 12 år (Tyskland)',
    da: 'Fra 12 år (Tyskland)',
    sv: 'Från 12 år (Tyskland)',
    fi: 'Yli 12-vuotiaille (Saksa)',
  },
  'FSK 16': {
    en: 'Released from age 16',
    fr: 'À partir de 16 ans (Allemagne)',
    de: 'Freigegeben ab 16 Jahren',
    es: 'A partir de 16 años (Alemania)',
    it: 'Da 16 anni (Germania)',
    nl: 'Vanaf 16 jaar (Duitsland)',
    pt: 'A partir dos 16 anos (Alemanha)',
    no: 'Fra 16 år (Tyskland)',
    da: 'Fra 16 år (Tyskland)',
    sv: 'Från 16 år (Tyskland)',
    fi: 'Yli 16-vuotiaille (Saksa)',
  },
  'FSK 18': {
    en: 'Released from age 18',
    fr: 'À partir de 18 ans (Allemagne)',
    de: 'Freigegeben ab 18 Jahren',
    es: 'A partir de 18 años (Alemania)',
    it: 'Da 18 anni (Germania)',
    nl: 'Vanaf 18 jaar (Duitsland)',
    pt: 'A partir dos 18 anos (Alemanha)',
    no: 'Fra 18 år (Tyskland)',
    da: 'Fra 18 år (Tyskland)',
    sv: 'Från 18 år (Tyskland)',
    fi: 'Yli 18-vuotiaille (Saksa)',
  },
};

function localizeCertificationMeaning(code, language, tmdbEnglishMeaning) {
  if (!code) return null;
  const short = langShort(language);
  if (short === 'en' && tmdbEnglishMeaning) return tmdbEnglishMeaning;

  const normalized = String(code).trim().toUpperCase();
  const row = CERT_MEANINGS[normalized];
  if (row) return row[short] || row.en || null;

  return short === 'en' ? tmdbEnglishMeaning || null : null;
}

module.exports = {
  localizeCertificationMeaning,
};
